### ISSUE TITLE
Evaluate necessity of `tabs` permission

### ISSUE THREAD

**Issue by pitkley** [huhu/search-extension-core#7]
For both manifests this repo currently defines the `tabs` permission as required:

https://github.com/huhu/search-extension-core/blob/519f42ed8ea63248a7e82b3ffd820349b15ffa22/manifest.libsonnet#L34-L36
https://github.com/huhu/search-extension-core/blob/519f42ed8ea63248a7e82b3ffd820349b15ffa22/manifest_v3.libsonnet#L32-L34

I recently got an update to my extension rejected by the Chrome Web Store because they (correctly!) flagged the `tabs` permissions as unnecessary. As per the [MV3 docs](https://developer.chrome.com/docs/extensions/mv3/declare_permissions/) (and this also applies [to MV2](https://developer.chrome.com/docs/extensions/mv2/declare_permissions/)):

> Gives your extension access to privileged fields of the [`Tab`](https://developer.chrome.com/docs/extensions/reference/tabs#type-Tab) objects used by several APIs including [chrome.tabs](https://developer.chrome.com/docs/extensions/reference/tabs/) and [chrome.windows](https://developer.chrome.com/docs/extensions/reference/windows/). In many circumstances your extension will not need to declare the `"tabs"` permission to make use of these APIs.

I verified that none of the features the aws-search-extension uses requires these extended permissions and removed them in <https://github.com/pitkley/aws-search-extension/commit/f7ab2f15c9b48ebd60be1a662aad0ab8d2299885>, after which the CWS approved my update.

I'm not sure if any of your or the other community extensions make use of the privileged tabs-APIs, but I still feel like the core manifest should not require that permission outright, requiring a workaround to remove it. WDYT?

**Comment by Folyd** [comment]
Thanks for the suggestion. 👍  Indeed, declaring the `tabs` as default permission is inappropriate for all downstream extensions. I'll fix this in the next PR.
